# -*- coding: utf-8 -*-
#
# Autocrypt documentation build configuration file, created by
# sphinx-quickstart on Fri Nov 11 22:05:17 2016.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
# sys.path.insert(0, os.path.abspath('.'))

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    #'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.viewcode',
    #'sphinx.ext.githubpages',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The encoding of source files.
#
# source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = 'contents'

# General information about the project.
project = u'Autocrypt'
copyright = u'2016-2024 the Autocrypt team, under <a href="https://creativecommons.org/publicdomain/zero/1.0/">CC0 license</a>'
author = u'the Autocrypt team'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#

# the version of the Autocrypt specification
specversion = u'1.1.0'

# The short X.Y version.
version = specversion
# The full version, including alpha/beta/rc tags.
release = specversion


# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
#
# today = ''
#
# Else, today_fmt is used as the format for a strftime call.
#
# today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']
pygments_style = 'sphinx'

todo_include_todos = True


# -- Options for HTML output ----------------------------------------------

html_theme = 'alabaster'
html_css_files = ['custom.css']

html_theme_options = {
  'logo':'../images/autocrypt_logo.png'
}

html_favicon = 'images/favicon.ico'
html_static_path = ['_static']
html_sidebars = {
    'index': [
        'sidebarintro.html',
        'globaltoc.html',
        'searchbox.html'
    ],
    '**': [
        'sidebarintro.html',
        'globaltoc.html',
        'relations.html',
        'searchbox.html'
    ]
}

html_additional_pages = { 'index':'customindex.html' }

htmlhelp_basename = 'Autocryptdoc'

# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
     # The paper size ('letterpaper' or 'a4paper').
     #
     'papersize': 'a4paper',

     # The font size ('10pt', '11pt' or '12pt').
     #
     # 'pointsize': '10pt',

     # Additional stuff for the LaTeX preamble.
     #
     'preamble': '''
\\newcommand{\\autocryptrelease}{%s}
\\setcounter{secnumdepth}{3}
'''%(specversion,),

     # Latex figure (float) alignment
     #
     # 'figure_align': 'htbp',
     'sphinxsetup': 'verbatimhintsturnover=true',

     # we will include the table of contents explicitly
     'tableofcontents': '',

     # the generated index was useless, hide it:
     'printindex': '',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
#    (master_doc, 'autocrypt-web.tex', u'Autocrypt Website', u'autocrypt team', 'manual'),
    ('level1', 'autocrypt-spec-{}.tex'.format(specversion),
     u'Autocrypt Level 1 Specification', u'Autocrypt team, licensed CC0',
     'howto', False),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
#
latex_logo = 'images/aclogo.png'

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
latex_use_parts = False

# If true, show page references after internal links.
latex_show_pagerefs = True

# If true, show URL addresses after external links.
latex_show_urls = 'footnote'
# latex_show_urls = True

latex_domain_indices = False


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'autocrypt', u'Autocrypt Documentation',
     [author], 1)
]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'Autocrypt', u'Autocrypt Documentation',
     author, 'Autocrypt', 'E-Mail Encryption for Everyone.',
     'Miscellaneous'),
]


# -- Options for Epub output ----------------------------------------------

# Bibliographic Dublin Core info.
epub_title = project
epub_author = author
epub_publisher = author
epub_copyright = copyright

# A list of files that should not be packed into the epub file.
epub_exclude_files = ['search.html']


# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {'https://docs.python.org/': None}


def setup(app):
        staging = True
        try:
            if os.environ['TRAVIS_REPO_SLUG'] == 'autocrypt/autocrypt' and os.environ['TRAVIS_BRANCH'] == 'master':
                staging = False
        except:
            pass
        try:
            import git
            with git.Repo(search_parent_directories=True) as repo:
                if str(repo.active_branch) == 'master':
                    staging = False
        except:
            pass
