@startuml

autonumber
title "happy path" (1:1) sequence diagram

control Alice #blue
control Bob #red

note over Alice: <alice@a.example.com>
note over Bob: <bob@b.example.com>

Alice --> Bob:  Autocrypt: to=alice@a.example; prefer-encrypted=yes; key=AAA
activate Alice
activate Bob
note over Bob: save Alice key
deactivate Bob
deactivate Alice

note over Bob: use Alice key
Alice <- Bob: Autocrypt: to=bob@b.example; prefer-encrypted=yes; key=BBB
activate Bob
activate Alice
note over Alice: save Bob key
deactivate Alice
deactivate Bob

note over Alice: use Bob key
Alice -> Bob: Autocrypt: to=alice@a.example; prefer-encrypted=yes; key=AAA
activate Alice
activate Bob
deactivate Alice
deactivate Bob

note over Alice: Alice has Bob key
note over Bob: Bob has Alice key

@enduml
