@startuml

autonumber
title "Alice lose key sequence diagram"

control Alice #blue
control Bob #red

note over Alice: <alice@a.example.com>
note over Bob: <bob@b.example.com>

Alice --> Alice: lost decryption key :-(
activate Alice
note over Alice: generate new Alices key
deactivate Alice

Alice -> Bob: Autocrypt: to=alice@a.example; prefer-encrypted=yes; key=XXX
activate Alice
activate  Bob
note over Bob: save Alices new key
deactivate Alice
deactivate Bob

@enduml
